### ISSUE TITLE
Can't get out from network

### ISSUE THREAD

**Issue by MidnightTale** [PolymerPorts/anshar-patch#1]
When trying to get out of the network, I can't get out and I get spam with log below.
```
[02:50:41] [Server thread/ERROR] (class_2600) Failed to handle packet net.minecraft.class_2851@36869bec, suppressing error
 java.lang.NullPointerException: Cannot invoke "carpet.fakes.EntityInterface.isPermanentVehicle()" because the return value of "net.minecraft.class_3222.method_5854()" is null
        at net.minecraft.class_3222.redirect$bdh000$carpet$setSneakingConditionally(class_3222.java:8542) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14218(class_3222.java:1119) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12067(class_3244.java:362) ~[server-intermediary.jar:?]
        at net.minecraft.class_2851.method_12369(class_2851.java:48) ~[server-intermediary.jar:?]
        at net.minecraft.class_2851.method_11054(class_2851.java:6) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:757) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```
# step to reproduce
1. Install both **Polymer Patch for Anshar** and **Anshar** on server(fabric-server-mc.1.20.4-loader.0.15.6-launcher.1.0.0) in with this mods list 
- abridged-fabric-1.20.x-1.1.1.jar
- adorabuild-structures-2.4.0-fabric-1.20.4.jar
- alessandrvenchantments-1.5.2.jar
- alloy-forgery-2.1.2+1.20.4.jar
- allsidedblocks-1.1.2.jar.n
- alternate-current-mc1.20-1.7.0.jar
- amethyst-tools-fabric+quilt-1.0+1.20.0-1.20.4.jar
- AnvilFix-20.0.1.jar
- appleskin-fabric-mc1.20.3-2.5.1.jar
- architectury-11.0.11-fabric.jar
- armor-stand-editor-2.3.0+1.20.3-rc1.jar
- async-locator-fabric-1.20-1.3.0.jar
- autoafk-1.2.5+1.20.1.jar
- balm-fabric-1.20.4-9.0.5.jar
- better-deepslate-ore-drops-2.jar
- betterloot-1.0.0+mc1.20.4.jar
- BetterThanMending-fabric-2.0.0.jar
- blahaj-fabric-1.20.4-0.4.1.jar
- blossom-blade-1.0.jar
- c2me-fabric-mc1.20.4-0.2.0+alpha.11.57.jar
- cardinal-components-api-5.4.0.jar
- charmofundying-fabric-7.0.0+1.20.2.jar
- Chunky-1.3.92.jar
- cloth-config-13.0.121-fabric.jar
- Continents_1.20.4_v1.1.4.jar
- convenient-mobgriefing-2.1.1.jar
- convenientdecor-0.3.0.jar.b
- coppernugget-1.20.4-1-fabric.jar
- Cropped-1.1.0.jar
- crossbow_expansion-1.20.4-1.2.1.jar
- DimThread-1.3.0+1.20.1.jar
- disableportalchecks-1.0.0.jar
- discord4fabric-1.20.4-1.11.0.jar
- dungeons-and-taverns-3.1.1.jar
- elementalenchantments-1.1.0.jar
- experimentalPerformance-0.1.1.jar
- explorify-v1.3.0-mc1.20.jar
- extrasponges-1.5.2.jar
- fabric-acb-1.1.2.jar
- fabric-api-0.95.4+1.20.4.jar
- fabric-carpet-1.20.3-1.4.128+v231205.jar
- fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
- factory-blocks-mod-1.0.0+1.19.jar.b
- fastminecart-1.0.0.jar
- foodtxf-1.20.4-1.5.4-fabric.jar
- ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
- formations-1.0.2-fabric-mc1.20.jar
- formationsnether-1.0.3.jar
- formationsoverworld-1.0.1.jar
- fullstackwatchdog-1.0.1+1.19.2-fabric.jar
- glideaway-1.0.2+1.20.4.jar
- glore-1.20.2-1.1.0.jar
- graves-3.2.1+1.20.3.jar
- head-name-fix-1.20-1.2.2.jar
- hit-the-dummy-1.0.jar
- HopoBetterMineshaft-[1.20.2-1.20.4]-1.2.0.jar
- HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7.jar
- HopoBetterUnderwaterRuins-[1.20-1.20.2]-1.1.4b.jar
- HorseBuff-1.20.2-2.1.3.jar
- hotshot-0.0.2.jar
- ibo-1.0.0.jar
- Icterine-fabric-1.20.3-4-1.3.0.jar
- Incendium_1.20.4_v5.3.4.jar
- InvView-1.4.14-1.20.4+.jar
- itemcommander-1.6.1+1.20.4.jar
- itemswapper-fabric-0.5.5-mc1.20.4.jar
- jline4mcdsrv-0.4.3.jar
- ledger-1.2.10.jar
- lithium-fabric-mc1.20.4-0.12.1.jar
- mariadb-jdbc-3.1.4+20230506-all.jar
- mc-server-description-4.2.1+1.20.1.jar
- mcpitanlib-2.0.5-1.20.4-fabric.jar
- midnightlib-fabric-1.5.3.jar
- modviewer-1.1.0+1.20.4.jar
- more_fossils-2.0.0.jar
- MoreCraftingTables-1.2.0+1.20.4-Fabric.jar
- mysql-jdbc-8.0.33+20230506-all.jar
- mythicupgrades-2.4.2+mc1.20.4.jar
- neruina-1.3.0-fabric+1.18.2-1.20.1.jar
- netheritebeacons-1.2.1.jar
- nice-mob-variants-1.44.jar
- noisium-1.0.2+mc1.20.x.jar
- owo-lib-0.12.3+1.20.3.jar
- poly-forgery-2.0.1+1.20.1-beta.1.jar
- polyconfig-0.3.7.jar
- polydecorations-0.2.1b+1.20.4.jar
- polydex-1.0.1+1.20.4.jar
- polyfactory-0.3.3-dev.build.126+1.20.4.jar
- polylootr-0.7.29.75+1.20.4.jar
- PolyMc-5.6.1+1.20.4.jar
- polymer-bundled-0.7.5+1.20.4.jar
- portablecrates-fabric-2.0.2+1.20.3-1.20.4.jar
- Quad-1.0.1+1.20.4-Fabric.jar
- RailOptimization1.1-1.20.4.jar
- RecipeCooldown-1.0.0.jar
- reel-0.1.3+1.20.4.jar
- repurposed_structures-7.2.4+1.20.4-fabric.jar
- RingsOfAscension-1.20.2-2.0.3.jar
- scaffolding-extension-1.1.7+MC1.19-1.20.4.jar
- secret-spectator-1.0.4.jar
- servercore-fabric-1.4.0+1.20.3.jar
- serveruifix-0.1.0+1.20.4.jar
- servux-fabric-1.20.2-0.1.0.jar
- shoutout-1.4.0.jar
- slime-1.8.jar
- slumber-1.2.0.jar
- spark-1.10.58-fabric.jar
- sparsestructures-2.1.2.jar
- sqlite-jdbc-3.41.2.1+20230506-all.jar
- starlight-1.1.3+fabric.f5dcd1a.jar
- Statement-4.2.9+1.14.4-1.20.4.jar
- Structory_1.20.2_v1.3.4.jar
- styled-chat-2.4.0+1.20.3.jar
- styled-nicknames-1.4.0+1.20.3.jar
- styledplayerlist-3.3.0+1.20.3.jar
- tectonic-fabric-1.20-v2.2.jar
- Telepost-1.14.jar
- TerraBlender-fabric-1.20.4-3.3.0.12.jar
- terralith-biome-saplings-1.1.0c.jar
- Terralith_1.20.4_v2.4.11_FABRIC.jar
- TimeStacker-fabric-1.1.3-1.20.4.jar
- toms_mobs-1.1+1.20.4.jar
- trimeffects-1.1.0-fabric.jar
- trinkets-3.8.0+polymerport.2.jar
- triqueapi-1.1.1+mc1.20.4.jar
- UndergroundBunkers-1.0.3-1.19.2-1.20.4-fabric.jar
- universal_shops-1.5.0+1.20.3.jar
- usbcharger_FABRIC_1_20_x.jar
- variantbeehives-1.2.jar
- viewdistancefix-fabric-1.20.4-1.0.2.jar
- vmp-fabric-mc1.20.4-0.2.0+beta.7.136-all.jar
- voicechat-fabric-1.20.4-2.5.1.jar
- wafflesscythes-1.0.0.jar
- wardentools-2.4.0+mc1.20.4.jar
- wits-1.2.1+1.20.3-fabric.jar
- WlodzimiersBlocks-1.1.2+1.20.4.jar
- worldedit-mod-7.3.0-beta-04.jar
- worldspecificviewdistance-0.2.1+1.20.4.jar
- yet-another-config-lib-fabric-3.3.2+1.20.4.jar
2. Open servers
3. Enter servers and build beacon
4. Jump on top beacon
5. Get stuck in air
https://cdn.hynse.net/public/videos/2024-02-29%2003-11-56.mp4

**Comment by Patbox** [comment]
Fixed in 0.0.15.1
