### ISSUE TITLE
Game crash issue

### ISSUE THREAD

**Issue by SAGUMEDREAM** [PolymerPorts/anshar-patch#2]
When I enter beacons and press shift to exit, the game crashes.

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-04-24 13:37:48
Description: Ticking Particle

java.lang.ClassCastException: class com.lgmrszd.anshar.transport.TransportGateParticle cannot be cast to class net.minecraft.class_677$class_680 (com.lgmrszd.anshar.transport.TransportGateParticle and net.minecraft.class_677$class_680 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @20398b7c)
	at net.minecraft.class_677$class_681.method_3030(class_677.java:178)
	at net.minecraft.class_677$class_681.method_3031(class_677.java:203)
	at net.minecraft.class_677$class_681.method_3070(class_677.java:104)
	at net.minecraft.class_702.method_3059(class_702.java:415)
	at net.minecraft.class_702.method_3048(class_702.java:399)
	at net.minecraft.class_702.method_18126(class_702.java:372)
	at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354)
	at net.minecraft.class_702.method_3057(class_702.java:370)
	at net.minecraft.class_310.method_1574(class_310.java:2056)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_677$class_681.method_3030(class_677.java:178)
	at net.minecraft.class_677$class_681.method_3031(class_677.java:203)
	at net.minecraft.class_677$class_681.method_3070(class_677.java:104)
	at net.minecraft.class_702.method_3059(class_702.java:415)
	at net.minecraft.class_702.method_3048(class_702.java:399)
	at net.minecraft.class_702.method_18126(class_702.java:372)
	at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354)
	at net.minecraft.class_702.method_3057(class_702.java:370)
Mixins in Stacktrace:
	net.minecraft.class_677$class_681:
		me.flashyreese.mods.sodiumextra.mixin.particle.MixinFireworkParticle (sodium-extra.mixins.json)
	net.minecraft.class_702:
		net.fabricmc.fabric.mixin.client.particle.ParticleManagerMixin (fabric-particles-v1.client.mixins.json)
		com.lgmrszd.anshar.mixin.client.render.ParticleManagerMixin (anshar.client.mixins.json)
		net.fabricmc.fabric.mixin.client.particle.ParticleManagerAccessor (fabric-particles-v1.client.mixins.json)
		net.coderbot.iris.mixin.fantastic.MixinParticleEngine (mixins.iris.fantastic.json)
		net.coderbot.iris.mixin.MixinParticleEngine (mixins.iris.json)
		me.flashyreese.mods.sodiumextra.mixin.particle.MixinParticleManager (sodium-extra.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.ParticleManagerMixin (fabric-registry-sync-v0.client.mixins.json)

-- Particle being ticked --
Details:
	Particle: class_681, Pos (272.5,-53.5,693.5), RGBA (1.0,1.0,1.0,1.0), Age 0
	Particle Type: NO_RENDER
Stacktrace:
	at net.minecraft.class_702.method_3059(class_702.java:415)
	at net.minecraft.class_702.method_3048(class_702.java:399)
	at net.minecraft.class_702.method_18126(class_702.java:372)
	at java.base/java.util.IdentityHashMap.forEach(IdentityHashMap.java:1354)
	at net.minecraft.class_702.method_3057(class_702.java:370)
	at net.minecraft.class_310.method_1574(class_310.java:2056)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

**Comment by SAGUMEDREAM** [comment]
24.04 13:41:06 [Multicraft] KafuuChino0722 ran command 每日信息
24.04 13:41:06 [Server] Server thread/INFO Using Fabric Permissions API
24.04 13:41:06 [Server] Server thread/INFO Using Fabric Permissions API
24.04 13:41:06 [Server] Server thread/INFO ✚ multiplayer.player.joined
24.04 13:41:08 [Server] Server thread/WARN Can't keep up! Is the server overloaded? Running 2069ms or 41 ticks behind
24.04 13:41:11 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:11 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:11 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:11 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:12 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:12 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:12 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:12 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:12 [Server] Server thread/WARN KafuuChino0722 moved too quickly! -0.011780197416555893,-9999.0,0.0
24.04 13:41:25 [Server] spark-async-sampler-worker-thread/WARN Timed out waiting for world statistics

**Comment by unilock** [comment]
If you're using this mod on a server, you should not have Anshar nor this mod on your client.
